### ISSUE TITLE
Make the stable ("main") branch default

### ISSUE THREAD

**Issue by anthonylusardi-da** [obsidiansystems/ex-healthcare-claims-processing#56]
https://github.com/obsidiansystems/ex-healthcare-claims-processing/commit/c2fda6e28eb4a62049013d6b79faa047476dc443

As you can see triggers started to depend on python via `startTriggers.py` and other things broke as well with starting the UI. When starting from a fresh git clone and after running `make build` I get the following:

`launchers/automation`
```
Traceback (most recent call last):
  File "scripts/startTriggers.py", line 11, in <module>
    from damlassistant import get_package_id, start_trigger_service_in_background, kill_process, \
  File "/Users/anthonylusardi/software/testing/scripts/damlassistant.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Can we get a `main` or `stable` branch and set it as default so that new changes don't cause the project to break and start it from commit `19fe383b17c6bced93c06373aa6ce09e2353f2ff`?

**Comment by anthonylusardi-da** [comment]
Being fixed in upstream

**Comment by ApolloUnicorn** [comment]
cc @runeksvendsen

**Comment by richardkapolnai-da** [comment]
Fix has been merged in upstream (https://github.com/digital-asset/ex-healthcare-claims-processing/pull/126), thanks for your patience.

**Comment by runeksvendsen** [comment]
Thank you for the fix. digital-asset#126 has been merged to our `develop` via https://github.com/obsidiansystems/ex-healthcare-claims-processing/pull/64

Perhaps we should add something to CI that runs the launcher scripts in order to avoid issues like these in the future?

**Comment by anthonylusardi-da** [comment]
Great, and can we also have a `main` default branch where we commit once we know it's stable?

**Comment by richardkapolnai-da** [comment]
> Perhaps we should add something to CI that runs the launcher scripts in order to avoid issues like these in the future?

Absolutely. We already have `mvn verify`, which _almost_ does the job. However, on the CI that missing Python module is pre-installed, so would not have caught it. :disappointed:

**Comment by ApolloUnicorn** [comment]
@Ericson2314 thoughts on renaming `Master` to `Main` and making default?

**Comment by ApolloUnicorn** [comment]
@anthonylusardi-da now on `main`
